version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: org_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orgdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 10

  migrate:
    image: golang:1.26-alpine
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    working_dir: /migrations
    entrypoint: sh -c "apk add --no-cache git && go install github.com/pressly/goose/v3/cmd/goose@latest && goose -dir=/migrations postgres \"postgres://postgres:postgres@db:5432/orgdb?sslmode=disable\" up"

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/orgdb?sslmode=disable"

volumes:
  pgdata: